### ISSUE TITLE
Status GENERIC_ERROR

### ISSUE THREAD

**Issue by maccyber** [navikt/sporenstreks-frontend#403]
Når ett krav blir postet til `/list`, og statusen blir returnert, hender det at responsen gir status: `GENERIC_ERROR`

```json
[ {
  "status" : "GENERIC_ERROR",
  "validationErrors" : null,
  "genericMessage" : null,
  "referenceNumber" : null
} ]
```

Likevel kommer jeg til "Søknaden er mottatt." -siden.
Skjønner at det er gjort med tanke på at flere krav blir sendt inn, også via excel listen.
Men det er litt forvirrende og litt skummelt :-)

Tror det beste er - hvis det er mulig - og kun gi "Vellykket krav" hvis status = "OK".

Vet dog ikke hvordan dette fungerer med excel-skjema.
```json
[ {
  "status" : "OK",
  "validationErrors" : null,
  "genericMessage" : null,
  "referenceNumber" : "0"
} ]
```

**Comment by MrFjellstad** [comment]
Fikset!
